### ISSUE TITLE
ScalingNOW (Reddit Post) needs review 

### ISSUE THREAD

**Issue by YalorMewn** [Giveth/Communication#10]
# ScalingNOW!

The following is a brief summation of the 3 day event hosted by [Giveth](https://giveth.io/) and [Web3 Foundation](https://web3.foundation/) in March which brought together scaling solution developers and DApp teams to discuss how they can move the Ethereum world forward. 

### For a link to the entire 3 day event transcript [follow me.](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#7472) 

The event was a hit, but as probably you know it takes money to host great events, *so if you enjoyed this please send some ETH to support [ScalingNOW](http://scalingnow.giveth.io/)! This will enable us to continue reviewing scaling solutions.*

* #####Proposed [Solutions](https://medium.com/@web3/scalingnow-scaling-solution-summit-summary-be30047047bf) listed here. 

* #####Event [Videos](https://www.youtube.com/playlist?list=PL4Artm1rmCWGksgoRe6HF5d9eklC01IcC) listed here. 

### State Channels:

- [µRaiden](https://raiden.network/micro.html)
- [L4 with Counterfactual](https://counterfactual.com/)
- [FunFair](https://funfair.io/) 
- [Spankchain](https://spankchain.com/)
- [Decentraland](https://decentraland.org/) 

### Side Chains:

- [Parity Technologies with the Parity Bridge](https://www.parity.io/) 
- [POA Network](https://poa.network/)
- [Cosmos](https://cosmos.network/) 

### Other Scaling Solutions:

- [Truebit](https://truebit.io/)
- [Plasma](https://plasma.io/) 

### Discussion:

- [Cryptokitties 😸](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#ba1d) 
- [Unsolved Issues in State Channels](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#b1e1) 
- [Sidechains Overview](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#fe30) 
- [Transaction Incentivisation](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#d349)
- [Metamask UX](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#1803)
- [Discoverability and Reputation of Contracts](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#63e8)

### [Additional Resources.](https://medium.com/giveth/scalingnow-summit-transcript-ea5373be8523#e779) 

# Found this helpful?
*Please send some ETH to [support ScalingNOW!](http://scalingnow.giveth.io/) Your donations enable us to continue supporting solutions!* 💙

If you want to learn more about Scaling Solutions jump into the [Riot] (https://riot.im/app/#/room/#ScalingEthereum:matrix.org) channel. 

#####[Join our community](http://join.giveth.io/): by tackling interesting problems like this one you can help us positively impact charitable giving forever!

* Discover our [Site](http://giveth.io/) and [Wiki](https://wiki.giveth.io/)

* Fork our code on [Github](http://github.com/Giveth/)

* Follow us on [Medium](http://medium.com/giveth/), [Facebook](https://www.facebook.com/givethio), [Twitter](http://twitter.com/givethio) and [Reddit](https://www.reddit.com/r/giveth/)

####Help us Build the Future of Giving:  🤲🏼 [Donate directly](http://donate.giveth.io/) 🤲🏼 or buy a Ledger with our [affiliate link](https://www.ledgerwallet.com/products/ledger-nano-s?utm_source=&utm_medium=affiliate&utm_campaign=d663) ⏎

**Comment by krrisis** [comment]
hey could you add the link to the google doc again here? is perfect with the redditpreview. One thingie already: 3 day event -> '2-day event'
