### ISSUE TITLE
Funding Strategy

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#101]
- [x] Jess will start on a fundraising deck to continue on with Kris, some inspiration in [Giveth onepager](https://docs.google.com/document/d/1h6svnXrDdnci-aiinxhiG967RTm8BS1b1fRs_wxgl8Y/edit?usp=sharing) and [Giveth Mission (link to goals doc at the end!)](https://wiki.giveth.io/dac/mission)
- [x] First review of progress on Monday
- [ ] Kris to set up call with @GriffGreen to discuss budgets
- [x] Jess to make edits for Draft Version 2

**Comment by jessicazartler** [comment]
Thank you for the inspiration! Here is the deck draft so far - about half way done ish, but the outline is finished and wanted to get your feedback before I go further. We can see if you like the layout and work on content further upon review tomorrow. Looking forward to it! :) 

https://docs.google.com/document/d/1hKUnYi9eL6Tc-QtFZRDckF_io7IZ2A2X60-oac4iHj8/edit#

*GDoc is on anyone with link can view - let me know if you want to change this

**Comment by jessicazartler** [comment]
Kris and Jess discussed outline - Jess will make next round of edits for Kris' review
We also shared with Parker so he can give feedback, be in the loop, and use this doc as a starting point for the next round of grants. He can also use this document to see if putting in a full grant application is even worth the time and effort, so good for initial contacts in the grant process.

Out TARGET DEADLINE for content is 1ST week in November to then send to design

**Comment by jessicazartler** [comment]
@krrisis second round of edits finished if you want to have a look - still a few missing pieces we can briefly discuss tomorrow and keep working when I am back to work after my meditation retreat Oct. 26
Thank you! :)

**Comment by krrisis** [comment]
Call coming up with @jessicazartler & @mroberts10 tmrw for next steps

**Comment by krrisis** [comment]
Overview doc that also holds the links to deck & partners [here](https://docs.google.com/document/d/1HqAMpG4r07pDBqorkDGYXZm-rscG6J8Pef8JU-PTD3k/edit?usp=sharing)

**Comment by krrisis** [comment]
Ongoing during the weekly Friday meetings with Dani & Griff & Michael & Kris
