### ISSUE TITLE
Feedback to live website

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#105]
- Plz create issues in the site repo for changes
- text edit feedback can go to Kris 

Kris & Griff have direct text edit access and will be working on this in the coming days
Kris will also create github issues in the coming days

**Comment by geleeroyale** [comment]
Before we do it with Issues, I would love to have a 1-on-1 with Kris for the first review, because there might be many changes

**Comment by GriffGreen** [comment]
Can we do the changes in this google doc? https://docs.google.com/document/d/13kY4NK-vU-v_kLv3NSeiMwOGG3jiv22is8XdzQ9NIjo/edit?usp=sharing
