### ISSUE TITLE
Backup videos from our channel

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/Communication#107]
Ok - I found something that we could use to download our videos. It does not seem to parse lists, but it can download all the videos in a playlist.

https://itsfoss.com/download-youtube-linux/

**Comment by krrisis** [comment]
Cool - can this run automatically?

**Comment by csggene3** [comment]
I'd be interested in helping with this as well.

**Comment by Pol-Lanski** [comment]
I don't think we can fit them in our GDrive... should we create a hard backup in one of our hard drives or you were thinking on some other platform?

**Comment by csggene3** [comment]
I was thinking of depositing them on a private hard drive at my own location to have an offline safe depository but that was just a thought...

**Comment by csggene3** [comment]
I have tons of unused drives that could be dedicated to this.

**Comment by csggene3** [comment]
Plus I have a GDrive One account with nothing on it if we wanted some online for online serving and not just safe keeping.

**Comment by Pol-Lanski** [comment]
I'd say by all means start filling up these disks!

**Comment by csggene3** [comment]
Rodger dodger.

**Comment by krrisis** [comment]
yes! I'd do that, see if the program @geleeroyale mentioned above could help, if not, don't hesitate to ping him. He most definitely also has thoughts on where to store them but starting locally is perfect. thx so much Gene!!

**Comment by geleeroyale** [comment]
It would be awesome if somebody of you guys runs the scraper. 

Also if that somebody starts to store it on a hard drive, we could use [syncthing](https://syncthing.net/) to share the folder.

**Comment by krrisis** [comment]
hey @csggene3 did you make any progress on this? thx!

**Comment by FrederikBolding** [comment]
I threw something together in Python here if you want to use it @krrisis - https://www.dropbox.com/s/py8td1utd6h8b6q/Giveth%20YouTube%20Backup.zip?dl=0

It can be run with Python3 by running the backup.py file in the pytube folder. Could probably be cleaned up at some point, but I had to customize the library a bit, and therefore had to include the source 😄

**Comment by FrederikBolding** [comment]
A repo has been created for the project here: https://github.com/Giveth/youtube-video-backup

**Comment by FrederikBolding** [comment]
I created an issue to discuss storage solutions here: https://github.com/Giveth/youtube-video-backup/issues/2
