### ISSUE TITLE
DATT Podcast

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#115]
https://www.dattpodcast.com/

**Comment by krrisis** [comment]
Ongoing at dattpodcast.com

**Comment by krrisis** [comment]
@geleeroyale has content from görlicon - @bowensanders  from aracon--> will let them add this

**Comment by bowensanders** [comment]
From Bruce - this is the current show layout idea
DATT network
— Web3 show
— What The Fork? show
— Aracon show
 
I'm hoping that there will be a "random" show on there too, to feature one-offs and content ("Decentralized Surprise!" has been tossed around)

**Comment by krrisis** [comment]
No update for burning man content? would still like to at least see vlad's talk go out (would not wait for any formal permission tbh)-- work is done (you did loaads on it) and is extreme good promo for our future camp and just DATT in general

**Comment by krrisis** [comment]
This is for now moving in a more for-profit direction plus they are not interested in 'one-offs' (which we often have), and bowen will be less involved, we will prob use the audio on the libsync account (paid by us).
