### ISSUE TITLE
Monthly Giveth Newsletter, signed Griff Green

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#118]
We need one person to take up a new role in our galaxy: informing the community of what's going on with Giveth on a monthly basis.

The job of this person could be to commit to: 

- attending the comms & gov meeting weekly and taking notes of what is going on 
- chasing & interviewing griff and let him talk on all that is happening in the giveth galaxy after having outlined & prepped some talking points
- ghostwriting a monthly 'editorial' in griff's name that we publish on our medium
- adding links to our other posts from that month 
- if possible also getting this sent through our new crm system (@geleeroyale & @danibelle working on this) 

Required: 
- at least a 3 month commitment to creating these to get the process going, if possible longer ofc
- describing this role in the giveth role sheet  & being someone we can count on 

Why do we need this?
- to keep our core audience (the ethereum community) up-to-date 
- to grow our community and giveth awareness
- to raise funds for the giveth galaxy through this awareness

**Comment by Joshfairhead** [comment]
Learning more about happenings via participatory action, especially in this way, is something I'd like to get involved in - it especially seems suitable as a good first role! May we give it a try?

**Comment by csggene3** [comment]
I'd like to be considered as well, if I'm not already too late to the party

**Comment by csggene3** [comment]
Could this be a possibly collaborative effort between Josh and I, or are we looking to make this a singular role?

**Comment by Pol-Lanski** [comment]
Unfortunately, with all the comms and governance meetings being pushed to even later, that sort of excludes Asia-based contributors to be able to join both meetings every time... but I think this is a very necessary step and I fullly support the newsletter! I can ghost-write pieces if necessary.

**Comment by csggene3** [comment]
I'm in California so the meetings are early morning for me but I've been able to get into both weekly regularly while feeling like a welcome participant. I've just been depressed lately and haven't attended this last week's.

**Comment by krrisis** [comment]
> Unfortunately, with all the comms and governance meetings being pushed to even later, that sort of excludes Asia-based contributors to be able to join both meetings every time... but I think this is a very necessary step and I fullly support the newsletter! I can ghost-write pieces if necessary.

Yeah @Pol-Lanski was a bit afraid that would be the case, it is high time for that universal giveth time in the galaxy, but we haven't made it to that dimension just yet. thx for all the support, as always!!

**Comment by krrisis** [comment]
Call happening TODAY!
