### ISSUE TITLE
crypto xmas promo

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#122]
write a step by step article based on this vid, both for mobile & desktop with screenshots 

https://www.youtube.com/watch?v=xWK-vTCjkfU (also integrate this)

plus link to the call for dapp cards - medium post coming up

**Comment by krrisis** [comment]
@paslar this https://medium.com/@cryptoxmas

**Comment by Danibelle** [comment]
Screenshots for creating and sending a card has been started..  edit access for any with this link:

https://docs.google.com/document/d/1Alv-HzMbpYEzvIrd17-3vaP8JHaC_qMvggoVGr2qkg8/edit?usp=sharing

**Comment by krrisis** [comment]
next: 
- dani ask to create profile so we can trace it on the dapp

**Comment by krrisis** [comment]
next: @Danibelle will check with adam to join the meeting tmrw
reminder for when it comes to the funds: post should also push people to still register in the dapp to trace their donations as @GriffGreen mentioned. thx!!

**Comment by krrisis** [comment]
survey link if u have worked on this, plz fill this in - https://goo.gl/forms/2rEYOd7bvmDijXLn1
