### ISSUE TITLE
Giveth Datafund Article Review

### ISSUE THREAD

**Issue by Danibelle** [Giveth/Communication#123]
Adam has been researching the new project coming up on Giveth, DataFund, and their strategy to create a Fair Data Society Decentralized Altruistic Community in conjunction with their campaigns.

He's written an article about it and needs review and comments!

Milestone for writing it is here:
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c12c07538756672b224ebd9

And the article is here:
https://docs.google.com/document/d/1rr6dxho4Ps4FsNdpGF35VTzQ7jWI4id1kWgPnqYz0RE/edit?usp=sharing

**Comment by krrisis** [comment]
hey @Danibelle I see this one is still here - when is this going out? enough feedback received? otherwise I'll quickly check (bit overloaded right now + I trust u guys ofc)
