### ISSUE TITLE
Mozilla Interview and podcast

### ISSUE THREAD

**Issue by mroberts10** [Giveth/Communication#126]
How to hold meetings - Google Hangouts

Who should come - widely advertise the hangout or simply Giveth community meeting group?
If a larger group, do we need a another platform with someone managing questions and the turning off mics etc.
Introductions: re: Giveth Griff/Bowen/Kris - re: Mozilla Mark Surman - Interview - Michael
Format: 10 min intros - 30min interview with questions decided by Giveth
20 min free for all but moderated
Opportunities

Social Coding Alliance with Mozilla?
Recording Event for podcast

separate local recording at each end
Type of questions

Mozilla how it grew into a large decentralized organization of Mozillians
How is Mozilla addressing the blockchain in its projects
Event 45min-1hour

**Comment by krrisis** [comment]
next, as discussed: 
- doodle for date 
- loomio for questions
- start of promo

**Comment by mroberts10** [comment]
Agreememnt to use google hangouts for the immediate team, and then stream things on youtube - have moderators collecting questions and ask question from the audience at the end of the chat.  Additional the interview with start with question posed by the Giveth team prepared in advance and through a loomio.
