### ISSUE TITLE
Odyssey Hackathon - 11-15 Apr.

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#128]
Possible SC project? 

More info via odyssey.org 
Pre-reg now, registration for pre-events now!

**Comment by krrisis** [comment]
Focus on token bonding curve

**Comment by Joshfairhead** [comment]
Just seeing this repo now! Needed a Zenhub indoctrination. Hells yeah on all the hack stuff, excited as to work on this :)

**Comment by Joshfairhead** [comment]
Bowen: please see [this thread](https://www.loomio.org/d/F7Pjp9Wv/odyssey-hack) for bits. Also feel welcome to join the fray ;)

**Comment by krrisis** [comment]
@JeffEmmett is owning the token bonding curves 
@Joshfairhead is talking on gov lab & other topics

**Comment by krrisis** [comment]
Griff proposes to present a working part by then and to continue hacking on this. 
BlockScience is a jury, Giveth will be participating - be aware of this
Griff: first work on the other hackathons

**Comment by Joshfairhead** [comment]
Edges are absorbed by competition. In capitalism, this creates a race to the bottom, in the commons it creates further abundance. Is it a problem that we live between the worlds?

**Comment by Joshfairhead** [comment]
Giveth - TEAM 1 have been accepted to the Odyssey Hackathon. They are building a Token Bonding Curve to "Tokenise the Odyssey Ecosystem", which is our first iteration on building sustainable funding mechanisms for the Crypto Commons and beyond. TEAM 2 is still in formation to build TCRs :)

**Comment by krrisis** [comment]
Team 2 is in formation (curation registry team) - Kay Emilie Chris & Roberto. Sponnet is in, Deam is possibly in as well. (Pando) ---> Track Nature 2.0

Team 3 is an integration team focusing on the Giveth DApp-- around a specific cause. --> Track tbd 

Working list of the teams -- https://docs.google.com/spreadsheets/d/1vjvgxk0Ua-zCtaAmTQSAji8xQipFdSBGfKEnXap5NFc/edit#gid=0

**Comment by krrisis** [comment]
Still organizing big time- Griff got a boat
no direct comms needed right now

**Comment by krrisis** [comment]
Next things for org:
- add twitter handle of all our participants in the sheet, possibly even github handle so we have all info in one place for comms 
- get a direct confirmation from each that they filled in their arrival & departure dates in the sheet
- get a direct (dm'd) confirmation from each participant that they have actually registered, that they did this under the correct name and edited if not correct. Can be an extra column in the boat sheet?
