### ISSUE TITLE
Jeff has an article that will go out next week

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#130]
https://medium.com/@jeffemmett/9584b40dfe30
Still being edited

**Comment by krrisis** [comment]
Hey @JeffEmmett @Jeff-Emmett, do you any review help on this? If so, we're here for you! <3

**Comment by Jeff-Emmett** [comment]
Hey kris, reviews are already in and waiting my time and focus to go in and make appropriate changes.  Flying home today, funeral tomorrow, probably a weekend off, and I'll hope to get back into the swing of things the following week.  Going to have a laundry list of things to take care of back in Canada, so might be another week or two before this goes live.  Apologies, life is still a mess at the mo!
