### ISSUE TITLE
Eth Denver 15-17 Feb.

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#132]
Possibility to build a team token-bonding curves --- griff will be looking into this

**Comment by krrisis** [comment]
- Griff will possible be a judge - TB curves, tbd --- will check with the team
- @vojtechsimetka  will give 1,5h talk on hacking the DApp - hope this will be streamed? plz let us know

**Comment by vojtechsimetka** [comment]
@krrisis will do, likely streamed + recorded but I'll ask.

**Comment by GriffGreen** [comment]
@mroberts10 and @Bowen and @Loie and @griffgreen are all going... anyone else?

**Comment by bowensanders** [comment]
As far as I know that's all of us :)  I'll ask if any of the social coders are going... but Josh DuChene is going to be there




---- On Wed, 06 Feb 2019 09:19:11 -0800 Griff Green <notifications@github.com> wrote ----




https://github.com/mroberts10 and https://github.com/bowen and https://github.com/loie and https://github.com/GriffGreen are all going... anyone else?

**Comment by krrisis** [comment]
Form a core team to work on frontend of a token bonding curve -- 4 people to build on this

**Comment by Joshfairhead** [comment]
Winner winner chicken dinners: https://kauri.io/collection/5c69c8c39c73740001dab899

**Comment by Joshfairhead** [comment]
Abbey is writing a medium post also. Might check in with her

**Comment by krrisis** [comment]
- Pactful won the social impact track (abbey corey seth & saga), bowen, joshua & griff were helping on it. 
- Burner Wallet - all funds we received are going to GraceAid on the DApp -- half to unicef, half to graceaid
