### ISSUE TITLE
Add Ahorralibre and MakerDAO to the list of friends on the website

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#147]
I will share this issue with them and try to get them to send the svg file needed here ;-D

**Comment by GriffGreen** [comment]
I was suprised i couldnt make an issue on the website's github...

**Comment by ghettodev** [comment]
Some tasty assets here you can snag: https://github.com/makerdao/Overview-of-MakerDAO-design#style-guide

**Comment by ElMejorge** [comment]
¡Hey Griff! Here are our logo and brand guidelines. Reach out if you need anything else, or have a general question. - Pascual

[alibre.zip](https://github.com/Giveth/Communication/files/2908186/alibre.zip)

**Comment by geleeroyale** [comment]
I added both projects to the friends section ❤️
