### ISSUE TITLE
Change Pinned Repos on Giveth Main Page

### ISSUE THREAD

**Issue by Danibelle** [Giveth/Communication#165]
Use Case: It would be helpful to Contributors for the Pinned Repositories to reflect those with current activity / where we most need support.

Change Requested: Communication since we meet on that every week should really be at the top. Replace Mini-Me with Communication.

If others pinned are not being used, both the Wiki and Galaxy are repositories that are actively open to revision.

![image.png](https://images.zenhubusercontent.com/5b588051b2890d2788b3d5de/d4cb1ae7-28a8-4922-8961-81717ec2468e)

**Comment by Danibelle** [comment]
Pin this Communication Repo!

**Comment by krrisis** [comment]
check, done! keeping the others bcs as you can see they have been forked quite a bit (esp minime).
