### ISSUE TITLE
BitIRA Interview Questions for Griff

### ISSUE THREAD

**Issue by Danibelle** [Giveth/Communication#166]
Email Request from Andrea at BitIRA - @GriffGreen to answer in Google Doc, questions pasted as well below.
https://docs.google.com/document/d/1QvPgWaFfnrslaFh0VqMbvMw-cdSHygnvYlN0N-GgiLw/edit?usp=sharing

Innovators in Crypto Interview: Griff Green, Giveth
February 2019

1. How did you first get interested in cryptocurrency and why did you first find appealing?

2. How did Giveth come about and what is the philosophy behind it?

3. What is the primary challenge to widespread adoption of the “gifting economy” concept?

4. Where do you envision that Giveth -- and the nonprofit sector of the economy in general -- will be 15 years from now, if this concept gains mass acceptance?

**Comment by krrisis** [comment]
call will work better
