### ISSUE TITLE
Giveth Sticker Reprint

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#169]
Dappnode would like to ship loads of partner stickers in their boxes, logically Giveth should be in there. 
We need 200 stickers for them, would be good to make some more for ourselves. 
Deadline requested.

**Comment by geleeroyale** [comment]
Can facilitate the print. I use [FLYERALARM](https://flyeralarm.at) from Vienna for all my stickers (commons carrot and revolution.eth stickers were printed there i.e.). Quality and color matching is top notch. Nice price as well ~ 37€ for 500 stickers. Needs a week to print.

**Comment by geleeroyale** [comment]
I just ordered 500 pcs of **vegan**!! outdoor stickers. I chose the purple color scheme, as all the others were never really part of the official palette. Will send them to Barcelona once they arrive at my place (printer only sends domestically).

Please note - I still need the address of new HQ - PM on Riot @lorelei1 @GriffGreen 

[EDIT] - Actual price was 42,36€ - will invoice via DApp
