### ISSUE TITLE
Lots of Griff Videos!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#171]
Griff Riff: https://twitter.com/thegrifft/status/1120774056834420736
Epicenter: https://twitter.com/epicenterbtc/status/1121013415105839104
Short ETHCapetown interview: https://twitter.com/GSpasov/status/1121036753589231617
Simon labeled as Griff :-D: https://twitter.com/GSpasov/status/1121036757057843201

**Comment by krrisis** [comment]
shared!
