### ISSUE TITLE
Photography at Barcelona retreat

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#180]
Does anybody have a nice camera and some skills they can bring to the retreat? 
Let's set up picture day at the hackerpad!

I'd love to take this opportunity where we are all in person to get great photos of the who of Giveth! I've been wanting for a while to see sweet, clear, bright portraits of Givethers... i just think there are so many uses that come up for this.
Here's your pre-warning to remember to bring your camera if this role is for you ^__^

**Comment by loietaylor** [comment]
@geleeroyale

**Comment by krrisis** [comment]
create a part or a subpage with headshots with @geleeroyale

**Comment by geleeroyale** [comment]
We have the pics now, but do we really have them on a website? I am quite ok with showing Giveth always as a bunch of people, where not necessarily everyone on the pic is in Giveth, or everyone who is a part of Giveth in the picture.

We were never asked for pictures, nor have I heard any negative sentiment on not showing faces on the website.

**Comment by krrisis** [comment]
continued in issue #200 & #201 -- thx that you made this one happen kay <3
