### ISSUE TITLE
Setting up a Communication Strategy for the hispanic markets

### ISSUE THREAD

**Issue by sepu85** [Giveth/Communication#184]
It is estimated that more than 437 million people speak Spanish as a native language, which qualifies it as second on the lists of languages by number of native speakers. from [wikipedia](https://en.wikipedia.org/wiki/Spanish_language). It is also noticed that the economical situation in countries in LatinAmerica is hardly needing a crypto-intervention as well as the decentralization of power and a fair distribution of resources.

Today I has been approach by two hispanic media blogs regarding not-Giveth related topics, which has triggered my idea/intention in kicking-off a Communication Strategy in spanish so Giveth can approach these new markets. The media blogs which I currently have an open channel are:
- www.criptonoticias.com : it is in the top 5 of the worldwide hispanic media blogs about cripto
- www.observatorioblockchain.com : I have a close collaboration with its director. It is a blog that is mainly tackling the spanish market.

In any case, plenty of hispanics media would be willing to give visibility and generate important information about what Giveth is doing for the world's future, specially about the Commons Stack! 

I do realize there are tons of priorities over there! Would like to leave this issue open to trace this opportunity for when the times comes :-)

**Comment by krrisis** [comment]
let's discuss in our call next week!!
