### ISSUE TITLE
Unicef Grant Video

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#190]
I'm considering going down to Tijuana early next month to chase/project manage/creatively inspire and direct - whatever is needed to make this submission video HAPPEN well before the deadline so we have a shot of ALibre devs getting funded that 100k :) 

sorry there is probably an issue for this already... just wanted to make sure this makes it into the mtg!

**Comment by krrisis** [comment]
- script already exists from our side -> @mroberts10 
- fill out the grant application form

**Comment by loietaylor** [comment]
@krrisis can help mentor them script wise on melding stories to create an effective video! I can do this as well but putting it here to remind myself we have you to call on!

**Comment by mroberts10** [comment]
Here is the link to the script - https://docs.google.com/document/d/1Kwm6srNJBjEy0erOT7O41IUtdmR8QD8xPKSdso4oP3o/edit?usp=sharing

**Comment by loietaylor** [comment]
Video is complete and the written form submission is in revision currently
