### ISSUE TITLE
DAPP blog post

### ISSUE THREAD

**Issue by mroberts10** [Giveth/Communication#194]
This would be the long awaited blog post on what happing with the DAPP.  We might wait to post this until we have a clearer path around funding, but we can put this together now regardless.

**Comment by krrisis** [comment]
would be good to start a doc with some bullet points on this michael - not sure what we can tell right now next to what is already in the latest dapp update on our medium? I would say: start with a roadmap on the wiki? that would already be extremely helpful to get funding I think? Could we put a timing on getting this done?

**Comment by krrisis** [comment]
closing this one for now - we can create a new one when we 'reboot'
