### ISSUE TITLE
Mission Statement 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#20]
- [x] Finalize Mission statement
- [x] Ask goals by Circle leads
- [x] Put Mission statement on wiki 
- [x] Review goals by Circle leads provide feedback
- [x] Link goals per Circle to roles document 
- [ ] Put goals on the wiki 
- [ ] Write article with mission statement & and goals (giveth galaxy)

**Comment by lorelei1** [comment]
had a preliminary convo with vojtech last night! let's solidify more what we are pulling from these goals convos with circle leads, then i will move fwd with asking the other leads. perhaps a good place to start is with the lead of the comms circle ;)

**Comment by krrisis** [comment]
yes! work on roles planned in 4 tomorrow :)
