### ISSUE TITLE
Work on pool of dedicated writers

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#22]
The idea is to have a number of writers that could help us out for DApp and other texts that need to be written. 

- [x] Kris to have a call with lanski
- [x] Kris to have a call with Vojtech
- [ ] Kris to have a call with Cleo 
- [x] Kris to have a call with Bowen

**Comment by parkwil89** [comment]
Hi Kris,

If you still need more people please add me to the list!

Best,
Parker

**Comment by jessicazartler** [comment]
Hey @krrisis  - do we still need more people to recruit for this?

**Comment by krrisis** [comment]
in progress - you're one of them ;-)
