### ISSUE TITLE
Roles review

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#27]
- [x] create a new document 
- [x] clean up roles for comms
- [x] discuss with lorelei 
- [x] present to circle leads

**Comment by lorelei1** [comment]
you created a new document? :-)

**Comment by krrisis** [comment]
that's the doc you have :)

**Comment by krrisis** [comment]
Roles meeting done on August 9, deadline for everyone to review roles & add is after burning man - lorelei will follow up on this and will add this responsibility to her role. Meeting notes [here](https://hackmd.io/_UmbcXbKRd-vACv8Bzt1rg)

**Comment by loietaylor** [comment]
thanks for the notes! i put 'em up on the wiki. https://wiki.giveth.io/protocol/roles-meeting-1/

**Comment by krrisis** [comment]
direct link to the roles etc https://docs.google.com/document/d/1Q-9Pi1RQX2g3RCW4EG08wRj3WPK8MHIj8Yn8aTGrEmc/edit?usp=sharing

**Comment by krrisis** [comment]
done
