### ISSUE TITLE
Aragon DAC - Community R&D

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#30]
- [x] bridge channels
- [x] set up bi weekly meeting
- [x] feedback on logo 
- [x] article to announce DAC
- [ ] ... 

All info in the Aragon DAC repo [here](https://github.com/aragon/aragondac-community)

**Comment by krrisis** [comment]
griff waiting for @Quazia to confirm - signing tbc

**Comment by GriffGreen** [comment]
Chris is working with Derek to get his feet wet in aragon, via technical documentation

**Comment by krrisis** [comment]
up & running - moving to backlog for that reason

**Comment by krrisis** [comment]
This is no longer happening :)
