### ISSUE TITLE
Decentral vids 2017

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#32]
- [x] review videos
- [ ] share videos

**Comment by ljg583** [comment]
All videos have been linked to this sheet to manage the content: https://docs.google.com/spreadsheets/d/1sugfFWmwLJRufCJ8-li03qYHFdrPjYChSFLmdekFvqQ/edit#gid=0

**Comment by ljg583** [comment]
They will be uploaded to the Decentralist Network YouTube as they are reviewed

**Comment by jessicazartler** [comment]
Errrrrmahgerrrrd what is this?

**Comment by krrisis** [comment]
@ljg583 are the ones of last year done?
