### ISSUE TITLE
Global Innovation fund 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#36]
Check if relevant: https://Globalinnovation.fund

**Comment by parkwil89** [comment]
This is potentially relevant but would require quite a bit of work and pre-positioning, is a lengthy and involved process and if for example Giveth was going to apply for the DApp, a lot of unanswered questions would need to be answered first.

If Giveth or any other projects are interested in applying for this and ready to be really dedicated to the proposal process please do send them my way and discuss and then potentially try to make something happen.

**Comment by vojtechsimetka** [comment]
We are interested, but there are more low hanging fruits here when it comes to financing. I have checked the application process and I don't think we can apply now. At minimum we need legal entity. It also seems to be investment not grant so as far as I understand there should be promise of return on that investment which is not our model as of now.

**Comment by krrisis** [comment]
ok thx vojtech - closing this one too for now, to be revisited in the future if we would at some point become a legal entity or change our model.
