### ISSUE TITLE
frontier technology 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#37]
check if relevant - Https://Medium.com/frontier-technology-livestreaming

**Comment by parkwil89** [comment]
Could potentially be relevant for a social coding project. Getting funding through the UK government (DFID) though obviously comes with a lot of legal strings. I would love to see a future where DFID wants to use the Giveth DApp to host a request for proposals but for now anyone they fund would need to be a legal entity (and likely one registered in the UK at that...).

If anyone is interested in applying for this though please do send them my way and we can discuss.

**Comment by deamme** [comment]
It's very fitting for the Giveth DApp according to this idea they have for blockchain integration: https://medium.com/frontier-technology-livestreaming/its-been-a-busy-month-since-my-last-post-and-things-are-really-moving-forward-2752622b01c6

**Comment by parkwil89** [comment]
Agreed but unfortunately this is what they are already doing, not something they are looking to fund right now. They put out open calls through DFID and have selected projects already and from what I can tell are not currently accepting new ones. Beyond that, a lot would need to change for Giveth to be eligible for UK government funding from these sources, most notably registering as a legal entity.

**Comment by deamme** [comment]
@parkwil89 I see, I didn't get that at a first glance. I don't see any projects in Social Coding that fits their requirement right now tbh.

**Comment by parkwil89** [comment]
@deamme Yeah they have it buried in there. Yeah I would have been surprised if any of them did fit the requirements but maybe someday! Otherwise for now I'll focus on grant opportunities from within the crypto community.

**Comment by krrisis** [comment]
Ok sounds good! then I'll close this one for now, thanks for looking into this guys!!
