### ISSUE TITLE
Stable Fund

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#41]
Griff applied for this 

https://medium.com/@stablefund/introducing-the-stable-fund-45-million-for-the-makerdao-ecosystem-def79afc4b2a

**Comment by krrisis** [comment]
relaunched by griff

**Comment by GriffGreen** [comment]
SUCCESS!!
MakerDAO committed to funding the DApp 5k in ETH now and 5k in DAI once that is possible :-D

**Comment by krrisis** [comment]
10K in total, last 5K when DAI works on the DApp!

**Comment by krrisis** [comment]
Link to dapp vision 8-pager  https://docs.google.com/document/d/1fr5Mb-VcfshgsnsVKXa6wxRfONHI6Uf2ssoqbzfUuKo/edit?usp=sharing
