### ISSUE TITLE
Team interviews 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#42]
// Aragon interview series

**Comment by jessicazartler** [comment]
What is this one about? Thanks! :)

**Comment by Danibelle** [comment]
Looks like we need to provide some Giveth team members for the Aragon Interview series..
http://blog.aragon.one/tag/team-interviews/
https://blog.aragon.org/nest-team-interviews-pando/
https://blog.aragon.org/nest-team-interviews-prysmatic-labs/
https://blog.aragon.org/nest-team-interviews-that-planning-suite/
https://github.com/aragon/aragon-monthly/issues/218

@jessicazartler

**Comment by krrisis** [comment]
Woops no this is to do something similar as what they did for Giveth. So closed too soon! 🙂
