### ISSUE TITLE
ETHBerlin SEPT 7-9

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#46]
- [ ] Contact @c1e0 and confirm us as a speaker - vojtech?

**Comment by krrisis** [comment]
Vojtech, Griff & Kris are in the US - would be great to have another Unicorn to represent Giveth!

**Comment by krrisis** [comment]
@deamme & @Quazia considering to go

**Comment by GriffGreen** [comment]
@adriamb will be there

**Comment by krrisis** [comment]
apparently submissions for speakers have been closed off for quite a while - hope @adriamb will present us well :)
