### ISSUE TITLE
Sovereign Identity Project

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#51]
Decentralizing identity, Catalunya as a test case

building team & tech spec, dappnode is part of this, working on 'identity blockchain' (incl aragon partnership), next: governance, org identities... (=the total package), 2 months calm ---> antigua could be a good  test case - make this a blockchain country

**Comment by Joshfairhead** [comment]
What needs help with here? Identity is fun :)

**Comment by krrisis** [comment]
I think this is still on hold for now, but good to keep it on the radar to come back to at some point.

**Comment by krrisis** [comment]
Closing this, not a direct comms issue
