### ISSUE TITLE
Eth Foundation Grant 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#53]
Txell & Yalor collecting info

https://blog.ethereum.org/2018/05/02/announcing-may-2018-cohort-ef-grants/

**Comment by parkwil89** [comment]
EF proposal to support social coding (including grants campaign) has been submitted, waiting for feedback.

**Comment by jessicazartler** [comment]
How's this going? Do you need support?

**Comment by Joshfairhead** [comment]
Any response from them?

**Comment by parkwil89** [comment]
Unfortunately it was not selected for funding.

**Comment by Joshfairhead** [comment]
Ok, so I'm good to close the issue? I'm uncertain of this process but going to click the close and comment button...
