### ISSUE TITLE
Status Incubate Grant

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#54]
Yalor & Txell collecting info 

https://status.im/incubate/

**Comment by krrisis** [comment]
hey @parkwil89 is this one Giveth as a whole could apply for?

**Comment by parkwil89** [comment]
@krrisis yeah possible but before deciding to proceed please take a look at the details. This would involve legal registration and moving Giveth into their incubator program from what I can tell. It's not just applying for funding it's applying to join their incubator program so in the past when we've discussed this people have moved against it. They may offer other options though so we could try to discuss with them but in general that seems to be program.

That being said if this is something you all do want I am happy to coordinate the proposal development

**Comment by krrisis** [comment]
Right! that was this one, thx for the update, let's see during comms tmrw then

**Comment by jessicazartler** [comment]
Any follow up for this? Sounds like a no?

**Comment by krrisis** [comment]
correct
