### ISSUE TITLE
Devcon 4 -- OCT 30 - NOV 2

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#58]
- [x] Team members to obtain tickets
- [x] Find location to stay
- [x] Presentation opportunities
- [ ] Production of new swag

**Comment by ljg583** [comment]
Accommodation is booked: Sokolovská 90/30, Karlín, 186 00 Praha-Praha 8, Czech Republic
Check in: Mon, Oct 29
Check out: Mon, Nov 5

**Comment by GriffGreen** [comment]
oops! 
made a separate issue for this. https://github.com/Giveth/Communication/issues/63 

most important part: https://docs.google.com/spreadsheets/d/1FbOytbsnwlR9JGDx1-cHqqc0XDydm_k7UvwAj6SY2Ls/edit?usp=sharing

**Comment by GriffGreen** [comment]
SIGN UP!!! We have limited spots!

**Comment by krrisis** [comment]
Side events
- Web3summit #75 
- status hackaton #59 
- FEM https://ethereumevents.global/events/2018-council-of-prague/

**Comment by krrisis** [comment]
So we are sponsoring this I see - what does this give us & what do we need @GriffGreen ?

**Comment by krrisis** [comment]
- Devcon sponsorship: logo on the site & banners + 2 free tickets
- Griff party & status hackaton give shirts

**Comment by krrisis** [comment]
All done
