### ISSUE TITLE
Future Projects to onboard

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#60]
Below (plz add in comments!) we will add projects that could be contacted and select for future onboarding on the DApp, after Devcon4

Focus is - for now - advised to be on **Ethereum-based or blockchain-savvy projects**, please take this into consideration. 

Next, as the ecosystem evolves, more projects should ofc be onboarded. 

Starting point: projects that contaced **us** - see list on our Google Drive (search 'becoming a DAC')
Ask projects that contact us to add themselves [here](http://bit.ly/GivethCommunity)

**Comment by krrisis** [comment]
[Dutch article](https://www.voordewereldvanmorgen.nl/duurzame-blogs/deze-ondernemers-gebruiken-nu-al-blockchain?utm_source=nwsbrief&utm_medium=email&utm_term=180720&utm_content=blockchain) with non-profits that are currently already deeply into blockchain

**Comment by krrisis** [comment]
Proposal by @satyavh - have a project that focus on electricity production (methane) https://www.forbes.com/sites/samlemonick/2017/09/29/scientists-underestimated-how-bad-cow-farts-are/

**Comment by Danibelle** [comment]
Link in the top comment for Projects to add themselves is not active?  I've been directing people to use this form as the very first step to show interest in Beta Testing as a user.  This link works: http://bit.ly/GivethCommunity

After receiving contact info from the form above, [this spreadsheet](https://docs.google.com/spreadsheets/d/1acfbmyiBpw1K141cH9ZBXaxNtoHEtw2fC6TvHFsnGoA/edit?usp=sharing) is a temporary 'CRM' solution for tracking engagement toward onboarding.

This sheet can also help track for fundraising - having a common database will help when we select a CRM tool that meets cross-functional needs.

**Comment by krrisis** [comment]
hey dani, fixed the link, it was the correct one, but for some reason not having added http threw an error. thx!

**Comment by krrisis** [comment]
Dani is creating a specific CRM issue (and solution :) )
