### ISSUE TITLE
Hire Onboarding person 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#61]
- [x] review Vojtech's [text](https://docs.google.com/document/d/1XuZ9-Zcvdab1WqwHXSoacWKIrNRRDasbOEc9KmnAzJY/edit?usp=sharing) by @GriffGreen @krrisis @Quazia  
- [x] share on all relevant media (ethlance etc?) --  by @vojtechsimetka 
- [ ] share on social (@krrisis)
- [ ] share in our community & beyond (@krrisis)

**Comment by vojtechsimetka** [comment]
I am giving up on ETH lance. Here is the final version, lets just share that
https://docs.google.com/document/d/1XuZ9-Zcvdab1WqwHXSoacWKIrNRRDasbOEc9KmnAzJY

**Comment by Danibelle** [comment]
@vojtechsimetka @krrisis I'd love to get this EPIC cleaned up and current and communicating my progress going forward.. :fast_forward:  Would you like me to just do that as the person in the role now?

My hire was on a month trial basis, and we have just completed that month, and I'm coming to Prague with y'all next month.. I *think* we're a go and would like to hear it here :scroll:

**Comment by vojtechsimetka** [comment]
@Danibelle please go ahead. I think we can just close this :).
