### ISSUE TITLE
Design Working Group

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#62]
Deam is leading a Design group!

**Comment by krrisis** [comment]
@geleeroyale is proposing to lead this and work together closely with deam & others 
He will also add goals & target audience to this issue
Possibly a Campaign on th DAC? tbc by @geleeroyale

**Comment by krrisis** [comment]
@geleeroyale will also check in the contributors list (bit.ly/givethmaker) who else should be invited
I will invite the aragon designer(s) via Quazia

**Comment by krrisis** [comment]
Joana & Alan came up with a contest proposal - see design contest

**Comment by GriffGreen** [comment]
we might want to work with the web3 design telegram group on this

**Comment by geleeroyale** [comment]
Said hello in the web3 design telegram group and invited them as well to our Riot channel. The group should in the next phase focus on actual work/assignments/feedback. We hope to distribute design as well as actual asset creation
