### ISSUE TITLE
Approved policies on wiki 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#67]
- [x] @geleeroyale will go through current wiki content & notes of previous meetings to see what is missing on the wiki when it comes to policies, rules & structure for clear onboarding of people 

- [x] @geleeroyale will update the wiki by writing this content - @krrisis volunteers to review anything & give feedback on structure

- [x] @krrisis will contribute to this issue through the work on the roles with lorelei, to bring more clarity for newcomers (see #27)

**Comment by geleeroyale** [comment]
site for approved policies: [https://wiki.giveth.io/policy/approved-policies/](https://wiki.giveth.io/policy/approved-policies/)

**Comment by krrisis** [comment]
@geleeroyale committed to keeping this updated so closing nxt week - @geleeroyale: hope you can add this as a role in the roles doc!
