### ISSUE TITLE
Update Donation Page

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#68]
- [ ] kris to review the updated design 
- [ ] kris to rewrite the text and include a clear reference to how money will be spend + link to DAC
- [ ] @geleeroyale to check with @perissology & @GriffGreen what the status is re:tokens & what to do

**Comment by jessicazartler** [comment]
How's this going - do you need help? :)

**Comment by krrisis** [comment]
updated in the website debriefing doc in #105  - closing this one!
