### ISSUE TITLE
ECF proposal submission for Social Coding

### ISSUE THREAD

**Issue by parkwil89** [Giveth/Communication#73]
Will soon be submitting a proposal to the ECF to support social coding and the grants campaign

**Comment by krrisis** [comment]
submitted!

**Comment by GriffGreen** [comment]
@YalorMewn any update?

**Comment by parkwil89** [comment]
@GriffGreen @YalorMewn 

Update: Interview with ECF took place 8/29, they asked for some follow up references, we still haven't heard anything back.

**Comment by parkwil89** [comment]
Unfortunately the proposal was not accepted by ECF

**Comment by krrisis** [comment]
Thanks for the update @parkwil89
