### ISSUE TITLE
Web3 Summit Hackerspace! (22-24 Oct 18)

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#75]
- [ ] No more speaking oppt BUT we have a hackernode - discuss materials needed
- [ ] Decide who can/should go (tickets €600) & apply for reduced tickets (loie kris & griff did)
- [ ] arrange lodging - they link to Michelberger Hotel & Hotel nhow Berlin

**Comment by vojtechsimetka** [comment]
I can go but I may need to leave 24th evening as the status hackathon starts 25.

**Comment by GriffGreen** [comment]
https://web3summit.com/program/hackerspace/ i wonder if we host a node if that will get us free tickets

**Comment by krrisis** [comment]
Griff applied for the space, I applied for a reduced ticket. more news coming up

**Comment by krrisis** [comment]
Node acquired!! 
Info from the application: 
What is the name of your Node? *
Blockchain Based Organizations NOW! - Giveth
What is the theme of your Node? *
Blockchain-Based entities (Orgs with no legal footprint) especially focused on decentralized not-for-profit blockchain projects on Giveth.
What props do you need to implement your Node? (e.g. Chairs, Tables, Projector etc.) *
chairs, tables, monitors, power strips, a projector or 2 would be awesome.
How will your Node contribute to the Web3 Summit? *
We will be showing off the progress of the projects that chose to skip the ICO route and just decentralize all the things the old fashioned way! I expect it to be a hacker space where people can work with projects like: Giveth DApp, Giveth Social Coding, Aragon DAC, Bright ID, EthSignals, EthKan, DAppNode, iden3, Open Source Block Explorers NOW!, Bridges between chains, and more! We will invite these groups to list the bounties they have to work on, give presentations on their progress, and try to keep some space open for projects we don't know about that show up during the conference.
What is the maximum amount of people you plan on hosting at your Node? *
70

**Comment by krrisis** [comment]
- Maybe create one banner --- blockchain based entities now -- needed both virtual & physical
- New title: blockchain states / orgs / nations ---> ask in comms channels 
- Roles: Griff can MC the room / presentation on Aragon DAC / Giveth 
- Card with the schedule + how to get there 
- Feedback from the team

**Comment by krrisis** [comment]
Working doc here https://docs.google.com/document/d/1jN7WCpiPlYemwwd13N1YVLzeWShZ2aacIxNUORRztcU/edit

**Comment by krrisis** [comment]
Done & it was a success - youtube vids online - podcasts being worked on
