### ISSUE TITLE
Status of the DApp

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#76]
- Wrote a draft ([here](https://docs.google.com/document/d/1kpeuf9xvsdQi4PQ9sgsA3T-CzPZSeTbKjEkLP6PRWjc/edit?usp=sharing)) - reviewed by @Danibelle <3 
- Next: integrate feedback later this week & send to griff & vojtech for final review

**Comment by jessicazartler** [comment]
Great job on the blog!!!! In the future - I am here to cowrite or for a second pair of eyes :)
