### ISSUE TITLE
Bountysource banner

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#77]
- opportunity for free banner space to get devs in 
- use this now or later - depends on the needs of the dev team - could also be a generic push for testers and/or to giveth makers form

**Comment by geleeroyale** [comment]
This is great for contributors!

Please put this issue forward to Riot channel - #giveth-design:matrix.org

**Comment by jessicazartler** [comment]
@krrisis how is this going? I think this could be great when we kick off our fundraising campaign :)

**Comment by krrisis** [comment]
Definitely! They needed this asap so submitted today, links to bit.ly/givethmaker for now, we can always change this in the future. Moving this into 'on hold' so we don't forget this nice one but actually DONE.

**Comment by Danibelle** [comment]
Is there a reason that bit.ly/givethmaker wouldn't be working right now?  I got an error not found.. 
![image](https://user-images.githubusercontent.com/39466970/46887535-e4a90d80-ce2b-11e8-9750-9be0202af26d.png)

**Comment by krrisis** [comment]
woops, that's just me being lazy, bitly is capital sensitive, it's http://bit.ly/GivethMaker

**Comment by krrisis** [comment]
live
