### ISSUE TITLE
Decentral talks & podcasts '18

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#79]
Kay is editing these
Will we be able to upload these on our own channel?

**Comment by krrisis** [comment]
joshua & bowen on podcasts - kay on decentralist

**Comment by geleeroyale** [comment]
**Videos:**
We started uploading them to a dedicated [Decentral Network youtube channel](https://www.youtube.com/channel/UCtjNP9e2gOYr_TXinywZn2Q) (as of now videos are on private)

**Podcasts:**
@bowensanders and Joshua are working on the podcasts

**Comment by jessicazartler** [comment]
Let me know if you need any support - My experience is on the video side -- worked in broadcast news for 8 years --- otherwise for podcasts, I know a few hosts that can spread out some content or who would be good resources if you need any support - good luck! :)

**Comment by krrisis** [comment]
@geleeroyale still working on this but will stop this, we will put it on the DATT podcast!
