### ISSUE TITLE
T-Shirt for DEVCON4

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/Communication#80]
Design is underway - assignee LydiaL (matrix username)
see communication about it on the design team Riot channel #giveth-design:matrix.org

**Comment by geleeroyale** [comment]
All praise goes to Lydia for making an incredibly inspired and artistic graphic for our devcon4 shirts.

We will order 200 pcs, white, bamboo viscose/cotton fairtrade shirts with black print - chest will have Lydia's graphic quite large, bottom seam will have a giveth.io logotype - we will get a mockup before final delivery to printing service.

**Comment by krrisis** [comment]
Closing - they look beautiful!
