### ISSUE TITLE
Fundraising Kickoff 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#81]
3 main areas: 
- Grants (Parker)
- Finding one big Giver 
- Crowdfunding (eg support us / sponsor & get a ticket to devcon)

**Comment by krrisis** [comment]
- Adam proposal: save percentage of donations (is possible with 
- sell one ticket for the real prize, other one builder cost to the DAC
- linds: asking for money & event org

**Comment by krrisis** [comment]
Wrote out my strategy thoughts [here](https://docs.google.com/document/d/1HqAMpG4r07pDBqorkDGYXZm-rscG6J8Pef8JU-PTD3k/edit?usp=sharing), first meeting held with Jessica, she'll continue working on her action items, we reconvene in two days.

**Comment by jessicazartler** [comment]
Added my notes to the doc and some action items along with the overall notes -- please see the top and what I added :)
 
Will work on getting action items created as issues here in Github and look forward to discussing next actions and moving things forward tomorrow 👍 💯

**Comment by krrisis** [comment]
kickoff done! check the epic for more
