### ISSUE TITLE
Initial qualification of future candidates

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#83]
Initial reach out to our database to see if interest still stands 

- you need to have a github account and/or a good feedback form 
- ethereum focused (!)
- focus mostly on the donors to start - and/or only projects that have a donor

possible candidates (griff): the ethereum foundation groups 
-social alpha
- ecf
- status incubate 

---> can attract their recipients

**Comment by Danibelle** [comment]
BrightID moved through expedited onboarding by 1:1 guidance with Vojtech - learnings around having Reviewers set up before creating Milestones and understanding the workflow end to end before starting it ;)   

First qualification implemented that new projects must have a Unicorn sponsor.  Second candidate moving through the process is Adria's - Reperkutum, a drumming social project for people with intellectual disabilities.

Following a process outlined [here](https://drive.google.com/open?id=1BLtoZH8Lq0n2Dq18W-c06oj8sARRV7lkwrm2SUUo7rw).

**Comment by jessicazartler** [comment]
@krrisis We talked about on our call -- here is the list Dani gave me of all the projects interested in getting onboarded -- also, Dani and I discussed, some may be good donation candidates as well. @Danibelle happy to assist in any way I can with this project. Will be talking with David Casey of Numundo next week so will fill you in about interests and potentially bringing them on board.

MAIN LIST https://docs.google.com/spreadsheets/d/1aNKVvGXwonHwd3xwqltwHMh-2qiEw7SADuDwSbr-FzI/edit?usp=sharing

DANIs REFINED LIST https://docs.google.com/spreadsheets/d/1acfbmyiBpw1K141cH9ZBXaxNtoHEtw2fC6TvHFsnGoA/edit?usp=sharing

**Comment by Danibelle** [comment]
Met with David at DevCon - he is ready to onboard!

**Comment by Danibelle** [comment]
Update: Reaching out to our existing contacts is back on the horizon with the selection and implementation of SuiteCRM.  Importing contacts is the next step then we can manage who we contact and what their interest/responses are!

**Comment by Danibelle** [comment]
Qualification is baked into the New User Process through an approval and whitelisting process between when new DAC's and Campaigns are drafted into Release first, then green lighted to be whitelisted.
