### ISSUE TITLE
RewardDAO 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#87]
- Dani catching up with lindsay
- Will sync with the circle leads
- Wants to reactivate the contributors' room

**Comment by csggene3** [comment]
Can I help here Dani or is this above me?

**Comment by Danibelle** [comment]
Looks like you are helping already @csggene3 by engaging in the Contributors room and sharing what you are up to!  

Another way to help, as you are looking through issues to find ones you can work on, would be to share about opportunities in other forums to attract more contributors -as you can see there is plenty to do :smile_cat:

**Comment by Danibelle** [comment]
Closing this, I'm actively tracking point recipients, seeking and engaging new contributors, and have initiated and/or implemented changes recommended by Linds through the WOF repo.
