### ISSUE TITLE
Hiring a Fundraising Person

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#89]
I would love to get a person for the comms department that only works on finding funders and has the main goal of being getting money to giveth, and the secondary goal of getting money on our dapp :-D

**Comment by GriffGreen** [comment]
Kris said he could be that person but if thats the case then we need to find someone who is able to take over his role.

**Comment by GriffGreen** [comment]
@Danibelle and @r33 (on riot) said they might have people they can pass the job description to :-D

**Comment by krrisis** [comment]
Jessica is going to support me for now in both comms & funding jobs for now if all goes well - first meeting held

**Comment by jessicazartler** [comment]
So happy to support!!! Do we still need to recruit anyone else? My business partner offered to also assist when we get rolling - he is great with numbers, can help us with the "Donation Deck" Kris and I will be creaing and has a lot of time at the moment as he is also in between projects. Perhaps we get the ball rolling and then see if he can join to support the efforts -- meantime will invite him to Riot and he will contact @GriffGreen --- so happy to be here! <3
