### ISSUE TITLE
Activists and Blockchain - A conversation with the Skeptics!

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#90]
@Danibelle , Kyle Graden from seedom, and I are collabing on a lil project responding to the common resistances and skeptical questions by activists, non-profit workers, and the type (MY type to be clear ;) when crypto and blockchain are brought up as tools for social change communities. We've all found ourselves running into the same walls when talking with these folks, and want to create a resource of answers to those questions. It'll probably become a Webinar or perhaps even a video skit someday, but for now it's a document brainstorming all the "problems" and solutions! We are super happy to have anyone contribute to this! https://docs.google.com/document/d/1tht-NFYweMdOWhZl7Y2g_H-1zI2tqVXhN25xkRGIWK8/edit

**Comment by GriffGreen** [comment]
AWESOME!!

**Comment by Pol-Lanski** [comment]
Sounds great. I have a bunch of NGOs that are terrified by the thought of increasing complexity in non-essential work and it would be great to have a standardized FAQ.

**Comment by loietaylor** [comment]
Yep! Glad to have your brain on it @Pol-Lanski . Can you think of certain concerns they have in particular and how those might be addressed?
