### ISSUE TITLE
Unicorn DAC

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#91]
It's time to vote on the Unicorn DAC and start this governance experiment! 

https://www.loomio.org/p/jkTKmJr1/unicorn-dac-voting-time-

**Comment by krrisis** [comment]
- Unicorn meeting coming up - we have 3 unicorns idea 
- Unicorn DAC will be created asap in the dapp 
- Loie will create a loomio 
- people should create Milestones!!
