### ISSUE TITLE
Conflict Resolution Process write up

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#92]
Reading and agreeing to the Conflict Resolution Process is one of the steps of being onboarded to the Unicorn DAC, but I haven't actually put this document on the giveth wiki yet! I need to record the process I hold for giveth which is a synthesis of Restorative Justice Circle practices modified for giveth's use, and put that process on loomio and then on the wiki once it gets voted in.

**Comment by krrisis** [comment]
This is live https://wiki.giveth.io/policy/conflict-res/
