### ISSUE TITLE
Roles Meet&Sheet write up

### ISSUE THREAD

**Issue by loietaylor** [Giveth/Communication#93]
We need a write up of the Roles meeting process and the Roles Sheet process (esp voting!) on the wiki! It's a complex and very useful process that we really need people to have full understanding of in order to utilize it well, so we need it documented publicly! Also so there is an easy place to refer Unicorn-hopefuls to read about it.

**Comment by loietaylor** [comment]
@krrisis this is your baby and you crafted it so beautifully so I would love to see this write up come from you! I'm happy to do the work of actually putting it on the wiki tho once you write it, if that makes life easier!

**Comment by krrisis** [comment]
Done - here, so no longer blocking :) https://docs.google.com/document/d/1JN8w73P0Ee-Zult8NM3eBgpnCVIWFS2KxMBq87aSAcg/edit?usp=sharing
