### ISSUE TITLE
Blockchain for Good Workshop

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#94]
There will be a panel or two, but after that it's about sharing experiences and focusing on bottlenecks: UX, fundraising, technical issues, etc

Livia & Dani will contact Kris for more 

https://pragueblockchainweek.cz/events/alice-good/

**Comment by jessicazartler** [comment]
Let me know if you need any support for this with planning or ideas :)

**Comment by krrisis** [comment]
Yes! waiting for news from the team

**Comment by krrisis** [comment]
streamed & live
