### ISSUE TITLE
Wall of Fame Updates

### ISSUE THREAD

**Issue by Danibelle** [Giveth/Communication#96]
Maybe these will be broken out into separate issues - I'll put it all here for now:

1.)  We'd like to conduct an experiment this month offering a form as an alternative to a video entry on the Wall of Fame.  Initial thought was just to share in the rooms and with those receiving points directly; it's been suggested that we add the link to the Wall itself with some text, perhaps "Received points this month? Please add your video below, and/or complete this form!"

Form is found here: https://docs.google.com/forms/d/1GdJGWMivV870gAEkf0rUol_Onxt_W4FE61gdYsMh-g8/edit

And ofc is open to review and suggestions.

2.) The "Week #" system is very difficult to translate to the RewardDAO worksheet for videos.  It would be helpful to have a page per month to align with the Reward Cycle - is there any reason not to change it from weeks to months?  If it's too many to a page, perhaps 1st through 15th is an option.  At minimum - adding the date range to each week would alleviate confusion.

3.) The Autoplay functionality of the videos is very difficult to manage in the RewardDAO spreadsheet.  Feedback from Lindsay is that they play when added to the sheet.  I have experienced this in going to the Milestones in the DApp as well, that they play when you click the Milestone.  Can the videos be set to where you have to click them to play?

**Comment by Danibelle** [comment]
I'm going to put these as 3 issues on the Wall of Fame repo now that I see there is one. 

Probably good to have here for refining how to communicate the changes as they are evaluated revised and implemented :)

**Comment by jessicazartler** [comment]
@Danibelle Should I do a Wall of Fame? Or this new doc? Or both? Thanks! :)

**Comment by krrisis** [comment]
hey @jessicazartler if wall of fame works for you, plz use it. If you have issues with the wall of fame, plz add them to the doc ;-) thx

**Comment by Danibelle** [comment]
I love Yes AND :)  Please do a video on the Wall @jessicazartler  you've got points!  

Updates on the three points in this issue are in the Wall of Fame repo.. 

1.) https://github.com/Giveth/wall-of-fame/issues/62
This one is done!

2.) https://github.com/Giveth/wall-of-fame/issues/63
This has been done, we're just having some problems with some configurations (like mine!) working properly.  Going into private mode seems to solve it for me.

3.) https://github.com/Giveth/wall-of-fame/issues/64
Working better, I'm going to track all the way through the milestone process before closing.

**Comment by Danibelle** [comment]
These changes are complete!
